sudo: required
services:
  - docker
before_install:
  - docker pull jrottenberg/ffmpeg:4.1-alpine
  - echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

script:
  - docker build -t cjy632258/php-ffmpeg-cli -f cli/Dockerfile cli

after_success:
  - docker push cjy632258/php-ffmpeg-cli